# Generated by Django 5.1.1 on 2024-09-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
    ]
