version: '3.8'
services:
  ipja-questionarios:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - 8003:8003
    env_file:
      - stack.env
    networks:
      - pi_default
    volumes:
      - chopp_db:/var/lib/postgresql/data
      - chopp_app:/app/

volumes:
  ipja_db:
  chopp_app:

networks:
  pi_default:
    external: true
