version: '3.8'
services:
  site-chopp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8005:8005"
    env_file:
      - stack.env
    networks:
      - pi_default
    volumes:
      - .:/app            # MONTA O CÓDIGO FONTE DO HOST DENTRO DO CONTAINER
      - chopp_data:/var/lib/postgresql/data
      - chopp_app:/app/media
volumes:
  chopp_data:
  chopp_app:
networks:
  pi_default:
    external: true
