version: '3.8'

services:
  site-chopp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8003:8003"
    # env_file:
    #   - stack.env
    networks:
      - cloudflare_default
    volumes:
      - postgres_chopp_data:/var/lib/postgresql/data
      - chopp_photos:/app/media

volumes:
  postgres_chopp_data:
  chopp_photos:

networks:
  cloudflare_default:
    external: true
