# Generated by Django 5.1.1 on 2024-09-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='collector_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
