# Generated by Django 5.1.1 on 2024-09-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('litros', models.PositiveIntegerField()),
                ('imagem', models.ImageField(blank=True, default=None, null=True, upload_to='chopps')),
                ('collector_id', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
