# Generated by Django 5.1.1 on 2024-09-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='collector_id',
        ),
        migrations.AddField(
            model_name='produto',
            name='servico',
            field=models.BooleanField(default=False),
        ),
    ]
