# Generated by Django 5.1.1 on 2024-09-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_collector_id_produto_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='descreva o produto/serviço', max_length=255),
        ),
    ]
