# Generated by Django 5.1.1 on 2024-09-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='litros',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
