# Generated by Django 5.1.1 on 2024-09-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_litros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='litros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
