# Generated by Django 5.1.1 on 2024-09-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='carrinho',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
