# Generated by Django 5.1.1 on 2024-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_evento_carrinho_evento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
