# Generated by Django 5.1.1 on 2024-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_usuario_bairro_remove_usuario_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
