# Generated by Django 5.1.1 on 2024-09-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_evento_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='carrinho',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
