# Generated by Django 5.1.1 on 2024-09-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_evento_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='carrinho',
        ),
    ]
