# Generated by Django 5.1.1 on 2024-10-23 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_carrinho_usuario_alter_evento_usuario_and_more'),
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='authentication.usuario'),
        ),
    ]
