# Generated by Django 5.1.1 on 2024-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_alter_transacao_transacao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='transacao_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
