# Generated by Django 5.1.1 on 2024-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorealizado',
            name='nome',
            field=models.CharField(default='não precisa preencher', max_length=100),
        ),
    ]
