# Generated by Django 5.1.1 on 2024-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_eventorealizado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorealizado',
            name='nome',
            field=models.CharField(blank=True, default='não precisa preencher', max_length=100),
        ),
    ]
