# Generated by Django 5.1.1 on 2024-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_eventorealizado_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemevento',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='imagemevento',
            name='ordem',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
