# Generated by Django 5.1.1 on 2024-10-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_imagemevento_options_imagemevento_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemevento',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagemevento',
            name='ordem',
        ),
    ]
